version: 2

builds:
  - binary: pzmonitor
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - formats:
      - binary

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
